name: twitter_api_v2
description: The most famous and powerful Dart/Flutter library for Twitter API v2.0.
version: 5.0.0
repository: https://github.com/twitter-dart/twitter-api-v2
issue_tracker: https://github.com/twitter-dart/twitter-api-v2/issues
homepage: https://github.com/twitter-dart
publish_to: none

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  http: ^1.2.2
  mime: ^2.0.0
  oauth1:
    git: https://github.com/Boehrsi/dart-oauth1
  universal_io: ^2.2.2
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_lints: ^6.0.0
  test: ^1.28.0
  build_runner: ^2.10.4
  json_serializable: ^6.11.2
  freezed: ^3.2.3
  import_sorter: ^4.6.0
  mockito: ^5.6.1

import_sorter:
  emojis: true
